### ISSUE TITLE
Reached 5 failures on API POST_graphql

### ISSUE THREAD

**Issue by annshress** [paypal/paypal-checkout-components#1201]
### Reached 5 failures on API POST_graphql. Circuit breaker is open now and API is not available.

Following [this](https://developer.paypal.com/docs/checkout/integrate/#5-capture-the-transaction) documentation.

Occassionally I receive following in the response on `mutation payWithCard`.

```
{
  "errors": [
    {
      "message": "Response not successful: Received status code 500",
      "name": "ServerError",
      "response": {
        "size": 0,
        "timeout": 0
      },
      "statusCode": 500,
      "result": {
        "name": "Error",
        "message": "Reached 5 failures on API POST_graphql. Circuit breaker is open now and API is not available.",
        "stack": "Error: Reached 5 failures on API POST_graphql. Circuit breaker is open now and API is not available.\n    at Breaker._run (/x/web/LIVE/graphqlnodeweb/node_modules/levee/lib/breaker.js:74:18)\n    at Breaker.run (/x/web/LIVE/graphqlnodeweb/node_modules/levee/lib/breaker.js:60:15)\n    at circuitCallback (/x/web/LIVE/graphqlnodeweb/node_modules/servicecore-hystrix/index.js:91:21)\n    at Timeout.ontimeout (/x/web/LIVE/graphqlnodeweb/node_modules/levee/lib/breaker.js:99:9)\n    at Timeout.<anonymous> (/x/web/LIVE/graphqlnodeweb/node_modules/async-listener/glue.js:188:31)\n    at ontimeout (timers.js:498:11)\n    at Timer.unrefdHandle (timers.js:611:5)"
      },
      "path": [
        "approveGuestPaymentWithCreditCard"
      ]
    }
  ],
  "data": {
    "approveGuestPaymentWithCreditCard": null
  },
  "extensions": {
    "developerNotes": [
      "Please include an 'x-app-name' header with your request that identifies your client.  (Ex: 'x-app-name': 'hermione')"
    ],
    "correlationId": "46b8c4a81af29"
  }
}
```

- paypal version: 5.0.71
- environment: sandbox
- browser: firefox quantum 69.0 64-bit
- issue also occurs at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)
- issue occur intermittently

Only tested with firefox

### Afterwards,
`Try again` button shows up and continuing in paypal's own window continues without any issue.

**Comment by khanghoang** [comment]
@annshress sorry for the late reply. Did you use `4111 1111 1111 1111` as the testing card? If you did, would you please try another card number before we're having some issues with that card **only on sandbox**.
