### ISSUE TITLE
HOSTED_FIELD_NOT_ALLOWED

### ISSUE THREAD

**Issue by nevenblazic** [paypal/paypal-checkout-components#1265]
Hi,
i am integrating paypal smart buttons to my web application and so far i have same issue with both sandbox and live. While paypal button itself works fine and i can process payment without any issues other option "Debit or Credit Card" is not working for me.

When i click on "Debit or Credit Card" and populate that form, after submit i am getting next error:

```
{ 
   "errors":[ 
      { 
         "message":"HOSTED_FIELD_NOT_ALLOWED",
         "path":[ 
            "approveGuestPaymentWithCreditCard"
         ],
         "stack":"Error: HOSTED_FIELD_NOT_ALLOWED\n    at /dependencies/xobuyernodeserv/cronus/scripts/dist/src/graphql/types/Mutation/Mutation.js:895:25\n    at Generator.next (<anonymous>)\n    at step (/dependencies/xobuyernodeserv/cronus/scripts/dist/graphql/types/Mutation/Mutation.js:108:191)\n    at /dependencies/xobuyernodeserv/cronus/scripts/dist/graphql/types/Mutation/Mutation.js:108:361\n    at propagateAslWrapper (/dependencies/xobuyernodeserv/cronus/scripts/node_modules/async-listener/index.js:504:23)\n    at /dependencies/xobuyernodeserv/cronus/scripts/node_modules/async-listener/glue.js:188:31\n    at /dependencies/xobuyernodeserv/cronus/scripts/node_modules/async-listener/index.js:541:70\n    at /dependencies/xobuyernodeserv/cronus/scripts/node_modules/async-listener/glue.js:188:31\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
         "checkpoints":[ 

         ],
         "meta":{ 

         },
         "contingency":true,
         "statusCode":200
      }
   ],
   "data":{ 
      "approveGuestPaymentWithCreditCard":null
   },
   "extensions":{ 
      "correlationId":"44e8402884f3f"
   }
}
```

Here is my code:
```javascript
paypal.Buttons({
                        // Set up the transaction
                        createOrder: function(data, actions) {
                            return actions.order.create({
                                purchase_units: [{
                                    amount: {
                                        value: self.subscriptionAmount
                                    }
                                }],
                                application_context: {
                                    shipping_preference: 'NO_SHIPPING'
                                }
                            });
                        },

                        // Finalize the transaction
                        onApprove: function(data, actions) {
                            return actions.order.capture().then(details => {
                                
                                }, error => {

                                });
                            });
                        },
                        onError: function (err) {
                        }

                    }).render(this.paypalElement.nativeElement);
```

So identical code is working fine with PayPal button but not with "Debit or Credit Card".

Neven

**Comment by cycle-path** [comment]
I'm facing the same issue. Please assist

**Comment by mib-kamel** [comment]
i have the same problem

**Comment by thyagomuris** [comment]
I have the same problem

**Comment by riverside** [comment]
I've exactly the same problem

**Comment by nevenblazic** [comment]
Reply from support:
```
I have reviewed your account and it shows that not all countries can pay without registration, those customers who can pay without registration will see option to pay with a credit card directly.
```

This is still a bug in js sdk, because its rendering option that is not going to work for all customers.

**Comment by fernandops26** [comment]
I have the same problem, this is critical.

**Comment by thyagomuris** [comment]
I found a behavior that generates this error, may be a coincidence but I think everyone can test and verify if the problem has been resolved.

I was using a test card I found on the internet and this error always pops up.

When I started using the cards generated in the paypal dasgboard (https://developer.paypal.com/developer/creditCardGenerator/), the error is no longer happening.

**Comment by IrvinFan** [comment]
I have the same finding as @thyagomuris did. You can't use common testing CC like 4111111111111111 or 4242424242424242. You have to use one that is linked to your sandbox buyer account: https://developer.paypal.com/developer/accounts/.

**Comment by thedavos** [comment]
Same problem, any update on this?

**Comment by nevenblazic** [comment]
It looks to me that this issue is only affecting specific markets/countries  and probably PP does not really care about those markets to actually fix the issue.

**Comment by danilosilvadev** [comment]
i'm having this too now, omg nobody found a solution until today?

**Comment by bluepnume** [comment]
Hi @khanghoang -- are you familiar with this one?

@nevenblazic -- are you still seeing this issue?

**Comment by khanghoang** [comment]
Folks, we've made a couple of changes from our side. Please let us know if the problem still occurs.
The majority of the `HOSTED_FIELD_NOT_ALLOWED` is because PayPal cannot process the guest transaction in the buyer's billing country.

**Comment by nevenblazic** [comment]
I can check in next 2-3 days, will let you know.

**Comment by khanghoang** [comment]
Folks, I will close the issue for now. Feel free to reopen it if it occurs again.

**Comment by polar-webspark** [comment]
I still have the same problem, if i chosen the Russia

**Comment by khanghoang** [comment]
@polar-webspark for RU, you need to load the sdk with `locale` param set to `xx_RU`
For example:
```

<!DOCTYPE html>

<head>
    <!-- Add meta tags for mobile and IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD&locale=en_RU"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            style: {
                color:  'blue',
                shape:  'pill',
                label:  'pay',
                height: 40
            }

        }).render('#paypal-button-container');
    </script>
</body>
 ```
