### ISSUE TITLE
[Bug] Installation issues while trying to setup in local machine

### ISSUE THREAD

**Issue by 3V3RYONE** [paypal/paypal-checkout-components#1823]
### 🐞 Describe the Bug
Hello, I am facing issue while setting up my local environment for paypal-checkout-components. Running the commands ```npm test``` gives me lots of errors. A

### 🔬 Minimal Reproduction  
  
1. git clone git@github.com:me/paypal-checkout.git
2. cd paypal-checkout
3. git remote add upstream git@github.com:paypal/paypal-checkout.git
4. git pull upstream
5. npm install
6. npm test

### 😕 Actual Behavior
Installation fails, with loads of error messages.  
Log :  
  
```  
Oops! Something went wrong! :(

ESLint: 8.5.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/home/jay2466/Documents/paypal-checkout-components/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2359:26)
    at Module._compile (/home/jay2466/Documents/paypal-checkout-components/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/jay2466/Documents/paypal-checkout-components/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @paypal/checkout-components@5.0.189 lint: `eslint --ext .js --ext .jsx src/ test/ *.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @paypal/checkout-components@5.0.189 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jay2466/.npm/_logs/2021-12-24T05_01_44_846Z-debug.log
npm ERR! Test failed.  See above for more details.  
```  

### 🤔 Expected Behavior
Proper Installation of the repository in local machine.  

### 🌍 Environment

- Browser version: - chromium
- OS version: - Ubuntu LTS 20.0.4

**Comment by 3V3RYONE** [comment]
bump
