### ISSUE TITLE
[Bug] Expected "export" or "export default" import/nocommonjs

### ISSUE THREAD

**Issue by jmichaelterenin** [paypal/paypal-checkout-components#1973]
### 🐞 Describe the Bug
I'm attempting to clone/work with paypal checkout. When I run npm test, I get the following error in.eslintrc.js:
3:1  error  Expected "export" or "export default"  import/no-commonjs

### 🔬 Minimal Reproduction
git clone https://github.com/paypal/paypal-checkout.git
cd paypal-checkout
npm install
npm test

OR

git clone https://github.com/paypal/paypal-checkout-components.git
cd paypal-checkout-components
npm install
npm test

### 😕 Actual Behavior
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @paypal/checkout-components@5.0.231 lint: `eslint --ext .js --ext .jsx src/ test/ *.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @paypal/checkout-components@5.0.231 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jmichaelt\AppData\Roaming\npm-cache\_logs\2022-07-19T23_49_04_477Z-debug.log
npm ERR! Test failed.  See above for more details.

### 🌍 Environment
npm version: 6.14.13
node version: 16.16.0
latest paypal version

### Affected browsers
N/A
### ➕ Additional Context
Which repo am I supposed to be cloning in order to use/test it locally?
And why doesn't anyone maintain these repos correctly anymore???

**Comment by jmichaelterenin** [comment]
You clearly need more than just babel-core, but now I'm running into more issues:
`node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\xampp\htdocs\paypal-checkout-components\$(npm'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at Object.<anonymous> (C:\Users\jmichaelt\AppData\Roaming\npm\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',`

**Comment by jmichaelterenin** [comment]
`\node.exe: bad option: --inline=false`

**Comment by jmichaelterenin** [comment]
`C:\xampp\htdocs\paypal-checkout-components\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.newLoader [as .js] (C:\Users\jmichaelt\AppData\Roaming\npm\node_modules\@babel\node\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at Object.<anonymous> (C:\Users\jmichaelt\AppData\Roaming\npm\node_modules\@babel\node\lib\_babel-node.js:176:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
`
